spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false


management:
  endpoints:
    web:
      exposure:
        include: refresh